{{HTML::style('assets/css/styles.css')}}
<div align='center'>
   <div>
   {{Form::label('titulo','Titulo:')}}
   {{Form::text('titulo')}}
   </div>
   <div>
   {{Form::label('prioridad','Prioridad:')}}
   {{Form::text('prioridad')}}
   </div>
    <div>
   {{Form::label('contenido','Contenido:')}}
   {{Form::textarea('contenido')}}
   </div>
   <div>
   {{Form::label('imagen','Imagen:')}}
   {{Form::file('imagen')}}
   </div>
   <div>
   {{Form::label('descripcion','Descripcion:')}}
   {{Form::text('descripcion')}}
   </div>
    <div>
   {{Form::label('costo','Costo:')}}
   {{Form::text('costo')}}
   </div>
   <div>
   {{Form::label('tiempoPubli','TiempoPubli:')}}
   {{Form::text('tiempoPubli')}}
   </div>

   <div>
   {{Form::submit($submit_text)}}
   </div>
</div>  